version: '3'

services:
  app:
    image: helloworld:ssh.1.5
    command: ["tail", "-f", "/dev/null"]
    ports:
      - "3002:3002" 
    volumes:
      - .:/app
      - ~/.ssh:/home/shinto/.ssh
    networks: 
      - backend

networks:
  backend: 
