# syntax=docker/dockerfile:1.2

FROM golang:1.17-buster AS base

LABEL maintainer="Shinto C V <cshintov@gmail.com>"

RUN apt-get update && apt-get install -y openssh-server

WORKDIR /app

# Creating user shinto (same as host) with home directory
# For avoiding permission issues for files created in container
RUN groupadd -g 1001 shinto
RUN useradd --create-home --shell /bin/bash -u 1001 -g 1001 shinto
RUN usermod -aG sudo shinto

RUN mkdir -p -m 0700 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
RUN git config --global --add url."git@github.com:".insteadOf "https://github.com/"

# Change gopath from /go to
ENV GOPATH=/home/shinto/go

# This only works with root user
COPY go.* .
RUN --mount=type=ssh \
    --mount=type=cache,target=/home/shinto/go/pkg/mod \
    go mod download

# Change owner of the GOPATH directory
RUN chown -R shinto:shinto /home/shinto/go

ENV GO_ENABLED=0

USER shinto
EXPOSE 3000
